/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FunnelCards {
        "cardBgColor": string;
        "cardFiveInfo": any;
        "cardFourInfo": any;
        "cardOneInfo": any;
        "cardSixInfo": any;
        "cardTextColor": string;
        "cardThreeInfo": any;
        "cardTwoInfo": any;
        "cardsNumber": number;
    }
}
declare global {
    interface HTMLFunnelCardsElement extends Components.FunnelCards, HTMLStencilElement {
    }
    var HTMLFunnelCardsElement: {
        prototype: HTMLFunnelCardsElement;
        new (): HTMLFunnelCardsElement;
    };
    interface HTMLElementTagNameMap {
        "funnel-cards": HTMLFunnelCardsElement;
    }
}
declare namespace LocalJSX {
    interface FunnelCards {
        "cardBgColor"?: string;
        "cardFiveInfo"?: any;
        "cardFourInfo"?: any;
        "cardOneInfo"?: any;
        "cardSixInfo"?: any;
        "cardTextColor"?: string;
        "cardThreeInfo"?: any;
        "cardTwoInfo"?: any;
        "cardsNumber"?: number;
    }
    interface IntrinsicElements {
        "funnel-cards": FunnelCards;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "funnel-cards": LocalJSX.FunnelCards & JSXBase.HTMLAttributes<HTMLFunnelCardsElement>;
        }
    }
}
